apiVersion: v1
kind: Service
metadata:
  name: healthylinkx-api-service
  labels:
    app: healthylinkx-api
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: healthylinkx-api